#-------------------------------
# General Site Settings
#-------------------------------
# Menu Section

menu:
- {title: Home, url: '#'}
- {title: About, url: '#'}
- {title: Store, url: '#'}

#-------------------------------
# SEO Section

seo:
  twitter-creator: '@mrdemonwolf'
  twitter-site: '@streamkingshq'
  type: 'website'
  google-analytics: UA-xxxx-1
  url:

#-------------------------------
# Twitch and SOTW Section
# Twitch API
twitchKey: o3rt6l6u2pgn1muzpgtuihxwset6y8
twitchUserID: 45335452
twitchBio: true
# Shows if twitchBio is set to false
customBio: I have always been fascinated with computers and design when I was 13. I was part of a community for a few years but moved on from them and decided to make my own. Had to learn how to design and layout a community.Thought this long journey I learned, failed many times, and gained a lot of knowledge
sotw-header:  Streamer Of The Week

#-------------------------------
# Social Icons and URlsh

social:
- {icon: 'fa-twitter', color: 'twitter-color', url: 'https://www.twitter.com/streamkingshq'}
- {icon: 'fa-twitter', color: 'twitter-color', url: 'https://www.twitter.com/streamkingshq'}

#-------------------------------
# Modified Date

modified-date: January 30, 2018

#-------------------------------
