#-------------------------------
# General Site Settings
#-------------------------------
# Menu Section

menu:
- {title: Home, url: '#'}
- {title: About, url: '#'}
- {title: Store, url: '#'}

#-------------------------------
# SEO Section

seo:
  twitter-creator: '@mrdemonwolf'
  twitter-site: '@streamkingshq'
  type: 'website'
  google-analytics: UA-xxxx-1
  url:

# Twitch API
twitchKey: o3rt6l6u2pgn1muzpgtuihxwset6y8
twitchUserID: 45335452

#-------------------------------
# Social Icons and URlsh

social:
- {icon: 'fa-twitter', color: 'twitter-color', url: 'https://www.twitter.com/streamkingshq'}
- {icon: 'fa-twitter', color: 'twitter-color', url: 'https://www.twitter.com/streamkingshq'}

#-------------------------------
# Modified Date

modified-date: January 30, 2018

#-------------------------------
