#-------------------------------
# General Site Settings
#-------------------------------
# Menu Section

menu:
- {title: Home, url: '#'}
- {title: About, url: '#about'}
- {title: Ofter, url: '#ofter'}
- {title: Join, url: 'https://discord.gg/9Uq4gAc'}
# menu-cta:
#   title: Join
#   url: 'https://discord.gg/9Uq4gAc'

#-------------------------------
# SEO Section

seo:
  twitter-creator: '@mrdemonwolf'
  twitter-site: '@streamkingshq'
  type: 'website'
  google-analytics: UA-xxxx-1
  url:

#-------------------------------
# Twitch and SOTW Section

# Twitch API
twitchKey: o3rt6l6u2pgn1muzpgtuihxwset6y8
twitchUserID: 132310560
twitchBio: false
# Shows if twitchBio is set to false
customBio: I am a outgoing, and fun person who enjoys playing league of legends on a daily basis. I also like to hula hoop for fun, and I am pretty good at doing so. If you want me to show you, I can hula hoop for you. Just ask! I love giving animals affection. They are sweet, cute, and much nicer than humans. ^-^
sotw-header:  Streamer Of The Week

#-------------------------------
# About Section

about:
  header: WELCOME TO THE FUTURE
  text: We are revolutionizing the way streamers connect to their audience and network, Stream Kings is a social platform for streamers of any kind. We look to enhance peoples networking abilities, through connection online, influential articles and inspirational stories. We launched in November 2017 with the goal to be the largest UK streaming social platform. In the first 4 days, we had 250 people interested in our project! We plan by June 2018 to have grown by 50% and have 1000+ people using our social platform. Start your journey with us today, we can’t wait for the future!
#-------------------------------
# Ofter Section

staff:
  - {name: Antonio, rank: Owner}
  - {name: Bamba, rank: Manager}
  - {name: Nathan, rank: Senior Staff}
  - {name: Brookelyn, rank: Staff}
  - {name: Dave, rank: Staff}
  - {name: Jay, rank: Staff}
  - {name: Toby, rank: Staff}


#-------------------------------
# Ofter Section

ofter:
  header:
  ofters:
    - {icon: , title: , text: ,}
    - {icon: , title: , text: ,}
    - {icon: , title: , text: ,}
    - {icon: , title: , text: ,}
    - {icon: , title: , text: ,}
    - {icon: , title: , text: ,}
    - {icon: , title: , text: ,}


#-------------------------------
# Social Icons and URls

social:
- {icon: 'fa-twitter', color: 'twitter-color', url: 'https://www.twitter.com/streamkingshq'}
- {icon: 'fa-twitter', color: 'twitter-color', url: 'https://www.twitter.com/streamkingshq'}

#-------------------------------
# Modified Date

modified-date: January 30, 2018

#-------------------------------
