#-------------------------------
# General Site Settings
#-------------------------------
# Menu Section

menu:
- {title: Home, url: '#'}
- {title: About, url: '#about'}
- {title: Ofter, url: '#ofter'}
- {title: Join, url: 'https://discord.gg/9Uq4gAc'}
# menu-cta:
#   title: Join
#   url: 'https://discord.gg/9Uq4gAc'

#-------------------------------
# SEO Section

seo:
  twitter-creator: '@mrdemonwolf'
  twitter-site: '@streamkingshq'
  type: 'website'
  google-analytics: UA-xxxx-1
  url:

#-------------------------------
# Twitch and SOTW Section

# Twitch API
twitchKey: o3rt6l6u2pgn1muzpgtuihxwset6y8
twitchUserID: 45335452
twitchBio: false
# Shows if twitchBio is set to false
customBio: I have always been fascinated with computers and design when I was 13. I was part of a community for a few years but moved on from them and decided to make my own. Had to learn how to design and layout a community.Thought this long journey I learned, failed many times, and gained a lot of knowledge
sotw-header:  Streamer Of The Week

#-------------------------------
# About

about:
  header: WELCOME TO THE FUTURE
  text: We are revolutionizing the way streamers connect to their audience and network, Stream Kings is a social platform for streamers of any kind. We look to enhance peoples networking abilities, through connection online, influential articles and inspirational stories. We launched in November 2017 with the goal to be the largest UK streaming social platform. In the first 4 days, we had 250 people interested in our project! We plan by June 2018 to have grown by 50% and have 1000+ people using our social platform. Start your journey with us today, we can’t wait for the future!


#-------------------------------
# Social Icons and URls

social:
- {icon: 'fa-twitter', color: 'twitter-color', url: 'https://www.twitter.com/streamkingshq'}
- {icon: 'fa-twitter', color: 'twitter-color', url: 'https://www.twitter.com/streamkingshq'}

#-------------------------------
# Modified Date

modified-date: January 30, 2018

#-------------------------------
