#-------------------------------
# General Site Settings
#-------------------------------
# Menu Section

menu:
# - {title: Home, url: '/'}
- {title: Store, url: 'https://clashattire.net/collections/StreamKings', _blank: false}
- {title: Stickers, url: 'https://northstik.co/shop?olsPage=t%2Fstream-kings',_blank: true}
- {title: Join, url: 'https://discord.gg/9Uq4gAc', _blank: true}
# menu-cta:
#   title: Join
#   url: 'https://discord.gg/9Uq4gAc'

#-------------------------------
# SEO Section

seo:
  twitter-creator: '@mrdemonwolf'
  twitter-site: '@streamkingshq'
  type: 'website'
  google-analytics: UA-xxxx-1
  url:

#-------------------------------
# Twitch and SOTW Section

# Twitch API
twitchKey: mw96b0edbexr9f6ri4mzoeygb60zx5
twitchUserID: 45335452
twitchBio: true
# Shows if twitchBio is set to false
customBio: 'I am a outgoing, and fun person who enjoys playing league of legends on a daily basis. I also like to hula hoop for fun, and I am pretty good at doing so. If you want me to show you, I can hula hoop for you. Just ask! I love giving animals affection. They are sweet, cute, and much nicer than humans. ^-^'
sotw-header:  Streamer Of The Week

#-------------------------------
# How Section

how:
  header: How will we help you?
  text: 'StreamKings is an organisation that is full of content creators and hard-working staff members, everyone in our community is supportive and will help you grow as much as they can! We have 110% commitment to our members and try our hardest to ensure their success.'

#------------------------------
# CTA Section

cta:
  header: We cant wait to meet you!
  sub-header: As soon as you join you will be politely greeted by staff members and other creators!

cta-button:
  title: JOIN NOW
  url: https://discord.gg/ykMfJBW

#-------------------------------
# Staff Section

staff-header: Our Staff
staff:
  - {name: Antonio, rank: Owner, twitter: 'https://www.twitter.com/'}
  - {name: Bamba, rank: Manager, twitter: 'https://www.twitter.com/'}
  - {name: Blaine, rank: Stream Manager, twitter: 'https://twitter.com/spartanxtv'}
  - {name: Nathan, rank: Senior Staff, twitter: 'https://www.twitter.com/mrdemonwolf'}
  - {name: Brookelyn, rank: Staff, twitter: 'https://www.twitter.com/'}
  - {name: Dave, rank: Staff, twitter: 'https://www.twitter.com/'}
  - {name: Jay, rank: Staff, twitter: 'https://www.twitter.com/'}
  - {name: Toby, rank: Staff, twitter: 'https://www.twitter.com/'}

#-------------------------------
# Ofter Section

ofter-image:
    image: jersey.png
    title: Stream Kings Jersey
ofter:
  - {header: 'Why choose us?', text: 'Stream Kings aims to provide you with all the tools necessary to become a successful, streamer, youtuber, creator & more! We have a fully dedicated staff team that operates 24 hours a day, 7 days a week that supports the growth of your talent! We firmly believe that everyone deserves an opportunity to be successful, and we want to provide that opportunity.'}
  - {header: 'Getting the most exposure from us!', text: 'When you want us to share your content make sure to either share it on discord with a member of staff or alternatively @ us! We will do our best to ensure your content gets the maximum exposure it can receive!'}

#-------------------------------
# Social Icons and URls

social:
- {icon: 'fa-twitter', color: 'default-social-color', url: 'https://www.twitter.com/streamkingshq'}
- {icon: 'fa-instagram', color: 'default-social-color', url: 'https://www.instagram.com/streamkingshq/'}
- {icon: 'fa-facebook', color: 'default-social-color', url: 'https://www.facebook.com/StreamKingsUK/'}

#-------------------------------
# Modified Date

modified-date: January 30, 2018

#-------------------------------
