#-------------------------------
# General Site Settings
#-------------------------------
# Menu Section

menu:
- {title: Home, url: '/'}
- {title: Store, url: 'https://clashattire.net/collections/StreamKings', _blank: true}
- {title: Forums, url: 'http://community.streamkings.ltd', _blank: true}
- {title: Discord, url: 'https://discord.gg/BMrV3KY', _blank: true}

# menu-cta:
#   title: Join
#   url: 'https://discord.gg/9Uq4gAc'

#-------------------------------
# SEO Section

seo:
  twitter-creator: '@mrdemonwolf'
  twitter-site: '@streamkhq'
  type: 'website'
  google-analytics: UA-xxxx-1
  url:

#-------------------------------
# Twitch Section

# Twitch API
twitchKey: mw96b0edbexr9f6ri4mzoeygb60zx5
twitchUserID: 181451817

#-------------------------------
# SOTW Section

sotw-1:
  header: Streamer Of The Week
  text:
    - 'Becoming streamer of the week is very simple! Stream! We look for the most active, engaging and passionate streamer. Originality is a key part and something we belive that can be developed, So don’t worry, if we think you have the potential then there is always a chance!'

sotw-2:
  header: How to be streamer of the week
  text:
    - 'Every week we as a community choose a streamer of the week! Someone that deserves special recognition for their amazing content. Receiving this reward is classed as a big honour amongst the community.'
    - 'We love to help the small streamers! So if you are new and starting out still try and get our recognition, you never know...'

#-------------------------------
# Hero Section

hero:
  header:  Are you a content creator?
  sub-header: StreamKings is here to help, you are one click away from growing your channel

#-------------------------------
# How Section

how:
  header: How will we help you?
  text: 'StreamKings is an organisation that is full of content creators and hard-working staff members, everyone in our community is supportive and will help you grow as much as they can! We have 110% commitment to our members and try our hardest to ensure their success.'

#------------------------------
# CTA Section

cta:
  header: We cant wait to meet you!
  sub-header: As soon as you join you will be politely greeted by staff members and other creators!

cta-button:
  title: JOIN NOW
  url: https://discord.gg/9Uq4gAc

#-------------------------------
# # Staff Section

# staff-header: Our Staff
# staff:
#   - {name: Antonio, rank: Owner, twitter: 'https://www.twitter.com/toniF_', has_twitter: true}

#-------------------------------
# How Section

ofter-image:
    image: jersey.png
    title: Stream Kings Jersey
ofter:
  - {header: 'Why choose us?', text: 'Stream Kings aims to provide you with all the tools necessary to become a successful, streamer, youtuber, creator & more! We have a fully dedicated staff team that operates 24 hours a day, 7 days a week that supports the growth of your talent! We firmly believe that everyone deserves an opportunity to be successful, and we want to provide that opportunity.'}
  - {header: 'Getting the most exposure from us!', text: 'When you want us to share your content make sure to either share it on discord with a member of staff or alternatively @ us! We will do our best to ensure your content gets the maximum exposure it can receive!'}

#-------------------------------
# Social Icons and URls
# # Icons supported are Twitter, Twitch, Spotify, Github, YouTube, Linkin, and Google Plus

social:
- {icon: 'fa-twitter', color: 'default-social-color', url: 'https://www.twitter.com/streamkingshq'}
- {icon: 'fa-instagram', color: 'default-social-color', url: 'https://www.instagram.com/streamkingshq/'}
- {icon: 'fa-facebook', color: 'default-social-color', url: 'https://www.facebook.com/StreamKingsUK/'}
- {icon: 'fa-discord', color: 'default-social-color', url: 'https://discord.gg/ykMfJBW'}

#-------------------------------
# Modified Date

modified-date: January 30, 2018

#-------------------------------
