# Video Header Section

video-header:
  header: Are you a content creator?
  sub-header: StreamKings is here to help, you are one click away from growing your channel

#-------------------------------
